### ISSUE TITLE
Add support for the `>>` operator (lshift)

### ISSUE THREAD

**Issue by mauro-balades** [snowball-lang/snowball#105]

**Comment by mauro-balades** [comment]
It bugs out because of generics finishing in `>>`. For example, `Vector<Class>>`

**Comment by TypeSafeSchwalbe** [comment]
Pretty sure it's fixed with https://github.com/snowball-lang/snowball/pull/108

**Comment by mauro-balades** [comment]
Fixed for now by changing it to `|>>`. https://github.com/snowball-lang/snowball/pull/108 is still open.
