### ISSUE TITLE
Docgenerator's modules should be inside their pages, not inside global module list.

### ISSUE THREAD

**Issue by mauro-balades** [snowball-lang/snowball#180]

**Comment by mauro-balades** [comment]
![Screenshot_20231226_100203](https://github.com/snowball-lang/snowball/assets/91018726/11790438-b8b9-4739-8101-85197ac19e4e)

Thanks @TypeSafeSchwalbe

**Comment by TypeSafeSchwalbe** [comment]
Not sure if the thanks is sarcasm or not, but either way no problem 🙂

**Comment by mauro-balades** [comment]
It wasn't sarcasm 🤣
