### ISSUE TITLE
Add support for enum types and pattern matching

### ISSUE THREAD

**Issue by mauro-balades** [snowball-lang/snowball#187]

**Comment by mauro-balades** [comment]
Heya!

I'm currently developing this issue at https://github.com/snowball-lang/snowball/pull/191. If you would like to contribute to it, you could join the Discord server and ask me questions there.

The only thing left would be adding support for pattern matching.

**Comment by gmottajr** [comment]
Could not find you there. Is there any link to your discord profile?

**Comment by mauro-balades** [comment]
https://discord.com/invite/nnShMQzR4b

**Comment by gmottajr** [comment]
Great, I'm there. Can you see me?

**Comment by mauro-balades** [comment]
yep. im the dot guy
