### ISSUE TITLE
Implement a JIT

### ISSUE THREAD

**Issue by mauro-balades** [snowball-lang/snowball#34]

**Comment by mauro-balades** [comment]
Maybe something like:

```
snowball run --jit
```

possible problems:

* Slow (maybe?)
* Might need to work out how to link symbols from other libraries

**Comment by mauro-balades** [comment]
@emm312 what do you think?

**Comment by emm312** [comment]
bros pinging me on literally every platform

**Comment by mauro-balades** [comment]
> bros pinging me on literally every platform

important bro

**Comment by emm312** [comment]
gonna make you wait now

**Comment by emm312** [comment]
hi

**Comment by mauro-balades** [comment]
sup

**Comment by emm312** [comment]
i'll make it

**Comment by mauro-balades** [comment]
the JIT?

**Comment by emm312** [comment]
no an ICBM written in snowball... we are in the jit issue of course it's the fucking jit

**Comment by mauro-balades** [comment]
![https://images-ext-2.discordapp.net/external/-_3UJWwpJqCYwP69RTqrlWdRZhtvMWSBj8MQiXsn5HM/https/media.tenor.com/k9sLhYL5XTsAAAPo/disappear.mp4]()

**Comment by mauro-balades** [comment]
maybe not a good time rn. Im currently rewriting the `Transformer` to have support for an `IRBuilder` im doing rn. 

https://github.com/snowball-lang/snowball/issues/38

I can't be bothered to fix git issues

**Comment by emm312** [comment]
don't you just have to touch the final Module generated

**Comment by mauro-balades** [comment]
You are right.in that case,u can still do the jit
