### ISSUE TITLE
unban user emm312 on discord server

### ISSUE THREAD

**Issue by emm312** [snowball-lang/snowball#61]
^

**Comment by mauro-balades** [comment]
u want to get a ban to the repo to?

**Comment by emm312** [comment]
sure

just unban me from the discord

**Comment by mauro-balades** [comment]
![Screenshot_20230721_095451](https://github.com/snowball-lang/snowball/assets/91018726/9b7c0c77-0bec-45ea-96d3-78a016dee8da)

is it really worth it?

**Comment by emm312** [comment]
if you rewrite it in rust

**Comment by mauro-balades** [comment]
I hope it was worth it
