### ISSUE TITLE
Add diverging functions

### ISSUE THREAD

**Issue by mauro-balades** [snowball-lang/snowball#65]

**Comment by 5ku11Cru5h3r** [comment]
Can you elaborate please

**Comment by mauro-balades** [comment]
> Can you elaborate please

Sure, what I meant is to add support for diverging functions (functions that never return)

https://doc.rust-lang.org/rust-by-example/fn/diverging.html

The TODO list this issue create would be:

- [ ] Add diverging type [`!`] (not sized, almost like a copy of `void`) 
- [ ] Functions with diverging types as return types can't return
