### ISSUE TITLE
"Continue" statment

### ISSUE THREAD

**Issue by mauro-balades** [snowball-lang/snowball#70]

**Comment by capedCrusaderr** [comment]
please brief us more about the issue

**Comment by mauro-balades** [comment]
```rs
for i in 0..10 {
   if i == 5 { continue }
}
```

**Comment by capedCrusaderr** [comment]
that's cool but in which file?

**Comment by mauro-balades** [comment]
> that's cool but in which file?
 
Sorry, I don't understand the question

**Comment by capedCrusaderr** [comment]
so sorry , I can't find the code

**Comment by mauro-balades** [comment]
No problem, this is just a TODO reminder for me, don't worry about it.
~ mauro




6 Aug 2023, 21:51 by ***@***.***:
